// <auto-generated />
namespace WikiHash.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangednameofcolumnArticleLinktoLinkinArticlestable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangednameofcolumnArticleLinktoLinkinArticlestable));
        
        string IMigrationMetadata.Id
        {
            get { return "201902261640488_Changed name of column ArticleLink to Link in Articles table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
